services:
  backend:
    image: yashpalkar11/course-manager-backend
    container_name: course_manager_backend
    ports:
      - "8000:8000"  # Maps port 8000 on the host to port 8000 in the container
    environment:
      - DJANGO_SETTINGS_MODULE=course_manager_backend.settings
      - POSTGRES_DB=course_manager
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    image: yashpalkar11/course-management
    container_name: course_management
    ports:
      - "3000:3000"  # Maps port 3000 on the host to port 3000 in the container
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:8000  # URL for the frontend to connect to the backend

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: course_manager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  # Maps port 5432 on the host to port 5432 in the container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

